plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

version = "1.0.1"

application {
    mainClass = 'org.example.MainApp'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

/*
 * =========================
 * FAT JAR (portable)
 * =========================
 */
tasks.register('fatJar', Jar) {
    group = 'build'
    description = 'Создать portable fat JAR (Swing)'

    archiveBaseName.set(rootProject.name)
    archiveVersion.set(version)
    archiveClassifier.set('')

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }

    // классы приложения
    from(sourceSets.main.output)

    // зависимости (если появятся в будущем)
    from({
        configurations.runtimeClasspath
                .filter { it.name.endsWith('.jar') }
                .collect { zipTree(it) }
    })
}

/*
 * Чтобы:
 * ./gradlew build
 * сразу делал fatJar
 */
tasks.build {
    dependsOn fatJar
}
